import type { MockupVariantSlug } from '@/lib/mockups/navigation'

export type FormVariantStyles = {
  label: React.CSSProperties
  input: React.CSSProperties
  textarea: React.CSSProperties
  select: React.CSSProperties
  checkbox: React.CSSProperties
  fieldGroup: React.CSSProperties
  error: React.CSSProperties
  submit: React.CSSProperties
  cancel: React.CSSProperties
  form: React.CSSProperties
  actions: React.CSSProperties
}

export const FORM_STYLES: Record<MockupVariantSlug, FormVariantStyles> = {
  sana: {
    form: { display: 'flex', flexDirection: 'column', gap: 20, maxWidth: 720 },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
    label: { fontSize: 13, fontWeight: 600, color: 'var(--sana-text-muted, #6b6578)' },
    input: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--sana-border, #e8e6ef)',
      fontSize: 15,
      fontFamily: 'inherit',
      background: '#fff',
    },
    textarea: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--sana-border, #e8e6ef)',
      fontSize: 15,
      fontFamily: 'inherit',
      minHeight: 100,
      resize: 'vertical' as const,
    },
    select: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--sana-border, #e8e6ef)',
      fontSize: 15,
      fontFamily: 'inherit',
      background: '#fff',
    },
    checkbox: { width: 18, height: 18, accentColor: 'var(--sana-accent, #7c5cfc)' },
    error: { color: '#dc2626', fontSize: 13, marginTop: 4 },
    actions: { display: 'flex', gap: 12, marginTop: 8 },
    submit: {
      padding: '10px 20px',
      borderRadius: 10,
      border: 'none',
      background: 'var(--sana-accent, #7c5cfc)',
      color: '#fff',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
    },
    cancel: {
      padding: '10px 20px',
      borderRadius: 10,
      border: '1px solid var(--sana-border, #e8e6ef)',
      background: '#fff',
      color: 'var(--sana-text, #1a1523)',
      fontSize: 14,
      fontWeight: 500,
      cursor: 'pointer',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
  linear: {
    form: { display: 'flex', flexDirection: 'column', gap: 16, maxWidth: 640 },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: 4 },
    label: { fontSize: 12, fontWeight: 500, color: '#8b8b8b', textTransform: 'uppercase' as const, letterSpacing: '0.04em' },
    input: {
      padding: '8px 12px',
      borderRadius: 6,
      border: '1px solid #2a2a2a',
      fontSize: 13,
      fontFamily: 'inherit',
      background: '#161616',
      color: '#ececec',
    },
    textarea: {
      padding: '8px 12px',
      borderRadius: 6,
      border: '1px solid #2a2a2a',
      fontSize: 13,
      fontFamily: 'inherit',
      minHeight: 80,
      resize: 'vertical' as const,
      background: '#161616',
      color: '#ececec',
    },
    select: {
      padding: '8px 12px',
      borderRadius: 6,
      border: '1px solid #2a2a2a',
      fontSize: 13,
      fontFamily: 'inherit',
      background: '#161616',
      color: '#ececec',
    },
    checkbox: { width: 16, height: 16, accentColor: '#5e6ad2' },
    error: { color: '#f87171', fontSize: 12 },
    actions: { display: 'flex', gap: 8, marginTop: 8 },
    submit: {
      padding: '8px 16px',
      borderRadius: 6,
      border: 'none',
      background: '#5e6ad2',
      color: '#fff',
      fontSize: 13,
      fontWeight: 500,
      cursor: 'pointer',
    },
    cancel: {
      padding: '8px 16px',
      borderRadius: 6,
      border: '1px solid #2a2a2a',
      background: 'transparent',
      color: '#8b8b8b',
      fontSize: 13,
      cursor: 'pointer',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
  qatalog: {
    form: { display: 'flex', flexDirection: 'column', gap: 20, maxWidth: 680 },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
    label: { fontSize: 14, fontWeight: 500, color: 'var(--color-text-sub-600, #64748b)' },
    input: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--color-stroke-soft-200, #e2e8f0)',
      fontSize: 15,
      fontFamily: 'inherit',
      background: 'var(--color-bg-white-0, #fff)',
    },
    textarea: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--color-stroke-soft-200, #e2e8f0)',
      fontSize: 15,
      fontFamily: 'inherit',
      minHeight: 96,
      resize: 'vertical' as const,
    },
    select: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid var(--color-stroke-soft-200, #e2e8f0)',
      fontSize: 15,
      fontFamily: 'inherit',
      background: 'var(--color-bg-white-0, #fff)',
    },
    checkbox: { width: 18, height: 18, accentColor: 'var(--color-primary-base, #f97316)' },
    error: { color: '#dc2626', fontSize: 13 },
    actions: { display: 'flex', gap: 12, marginTop: 8 },
    submit: {
      padding: '10px 20px',
      borderRadius: 10,
      border: 'none',
      background: 'var(--color-primary-base, #f97316)',
      color: '#fff',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
    },
    cancel: {
      padding: '10px 20px',
      borderRadius: 10,
      border: '1px solid var(--color-stroke-soft-200, #e2e8f0)',
      background: 'var(--color-bg-white-0, #fff)',
      color: 'var(--color-text-strong-950, #334155)',
      fontSize: 14,
      fontWeight: 500,
      cursor: 'pointer',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
  elevenlabs: {
    form: { display: 'flex', flexDirection: 'column', gap: 18, maxWidth: 720 },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
    label: { fontSize: 13, fontWeight: 600, color: '#64748b' },
    input: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      background: '#fff',
    },
    textarea: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      minHeight: 96,
      resize: 'vertical' as const,
    },
    select: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      background: '#fff',
    },
    checkbox: { width: 18, height: 18, accentColor: '#111827' },
    error: { color: '#dc2626', fontSize: 13 },
    actions: { display: 'flex', gap: 12, marginTop: 8 },
    submit: {
      padding: '10px 20px',
      borderRadius: 10,
      border: 'none',
      background: '#111827',
      color: '#fff',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
    },
    cancel: {
      padding: '10px 20px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      background: '#fff',
      color: '#334155',
      fontSize: 14,
      fontWeight: 500,
      cursor: 'pointer',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
  atlas: {
    form: { display: 'flex', flexDirection: 'column', gap: 20, maxWidth: 720 },
    fieldGroup: { display: 'flex', flexDirection: 'column', gap: 6 },
    label: { fontSize: 13, fontWeight: 600, color: '#64748b' },
    input: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      background: '#fff',
    },
    textarea: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      minHeight: 96,
      resize: 'vertical' as const,
    },
    select: {
      padding: '10px 14px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      fontSize: 14,
      fontFamily: 'inherit',
      background: '#fff',
    },
    checkbox: { width: 18, height: 18, accentColor: '#0d9488' },
    error: { color: '#dc2626', fontSize: 13 },
    actions: { display: 'flex', gap: 12, marginTop: 8 },
    submit: {
      padding: '10px 20px',
      borderRadius: 10,
      border: 'none',
      background: '#0d9488',
      color: '#fff',
      fontSize: 14,
      fontWeight: 600,
      cursor: 'pointer',
    },
    cancel: {
      padding: '10px 20px',
      borderRadius: 10,
      border: '1px solid #e2e8f0',
      background: '#fff',
      color: '#334155',
      fontSize: 14,
      fontWeight: 500,
      cursor: 'pointer',
      textDecoration: 'none',
      display: 'inline-flex',
      alignItems: 'center',
    },
  },
}
