/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    companies: Company;
    locations: Location;
    'asset-categories': AssetCategory;
    'asset-statuses': AssetStatus;
    'ticket-types': TicketType;
    employees: Employee;
    'maintenance-teams': MaintenanceTeam;
    assets: Asset;
    'asset-movements': AssetMovement;
    tickets: Ticket;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    locations: {
      children: 'locations';
      assets: 'assets';
      tickets: 'tickets';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'asset-categories': AssetCategoriesSelect<false> | AssetCategoriesSelect<true>;
    'asset-statuses': AssetStatusesSelect<false> | AssetStatusesSelect<true>;
    'ticket-types': TicketTypesSelect<false> | TicketTypesSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    'maintenance-teams': MaintenanceTeamsSelect<false> | MaintenanceTeamsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'asset-movements': AssetMovementsSelect<false> | AssetMovementsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Stored for future RBAC; MVP grants broad access to all authenticated users.
   */
  role: 'admin' | 'manager' | 'technician' | 'staff';
  /**
   * Create the employee record first, then link it here.
   */
  employee: string | Employee;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: string;
  /**
   * Auto-generated on create.
   */
  employeeId?: string | null;
  fullName: string;
  company: string | Company;
  jobTitle?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Optional link to a Payload admin user.
   */
  user?: (string | null) | User;
  team?: (string | null) | MaintenanceTeam;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  /**
   * Short code (e.g. STN, PIMMS)
   */
  code: string;
  /**
   * Leave empty for the group root (e.g. Stanton).
   */
  parent?: (string | null) | Company;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-teams".
 */
export interface MaintenanceTeam {
  id: string;
  name: string;
  company: string | Company;
  members?: (string | Employee)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  company: string | Company;
  /**
   * Group nodes organise the tree; only leaf locations hold assets and tickets.
   */
  isGroup?: boolean | null;
  /**
   * Parent must be a group location within the same company.
   */
  parent?: (string | null) | Location;
  /**
   * Optional label for what this node represents in the hierarchy.
   */
  kind?: ('region' | 'building' | 'floor' | 'zone') | null;
  /**
   * Locations nested under this group.
   */
  children?: {
    docs?: (string | Location)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Assets assigned to this location.
   */
  assets?: {
    docs?: (string | Asset)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Maintenance tickets for this location.
   */
  tickets?: {
    docs?: (string | Ticket)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  name: string;
  assetTag: string;
  /**
   * Owning company — may differ from the location company.
   */
  company: string | Company;
  location: string | Location;
  category: string | AssetCategory;
  status: string | AssetStatus;
  serialNumber?: string | null;
  tonnage?: number | null;
  custodian?: (string | null) | Employee;
  /**
   * Pre-fills ticket assignment when this asset is linked.
   */
  defaultTeam?: (string | null) | MaintenanceTeam;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-categories".
 */
export interface AssetCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-statuses".
 */
export interface AssetStatus {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  /**
   * Auto-generated on create.
   */
  ticketNumber?: string | null;
  title: string;
  description?: string | null;
  type: string | TicketType;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  status: 'open' | 'in_progress' | 'completed' | 'cancelled';
  reviewStatus: 'none' | 'pending' | 'verified' | 'rejected';
  company: string | Company;
  location: string | Location;
  asset?: (string | null) | Asset;
  reportedBy: string | Employee;
  reportedAt: string;
  assignedTeam?: (string | null) | MaintenanceTeam;
  assignedTo?: (string | null) | Employee;
  /**
   * Chronological log of comments, photos, and lifecycle events.
   */
  activity?:
    | {
        kind: 'comment' | 'photo' | 'completion' | 'review';
        author: string | Employee;
        body?: string | null;
        photos?: (string | Media)[] | null;
        createdAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-types".
 */
export interface TicketType {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-movements".
 */
export interface AssetMovement {
  id: string;
  /**
   * Auto-generated on create.
   */
  reference?: string | null;
  asset: string | Asset;
  company: string | Company;
  fromLocation?: (string | null) | Location;
  toLocation: string | Location;
  movedBy?: (string | null) | Employee;
  movedAt: string;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'asset-categories';
        value: string | AssetCategory;
      } | null)
    | ({
        relationTo: 'asset-statuses';
        value: string | AssetStatus;
      } | null)
    | ({
        relationTo: 'ticket-types';
        value: string | TicketType;
      } | null)
    | ({
        relationTo: 'employees';
        value: string | Employee;
      } | null)
    | ({
        relationTo: 'maintenance-teams';
        value: string | MaintenanceTeam;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'asset-movements';
        value: string | AssetMovement;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  employee?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  isGroup?: T;
  parent?: T;
  kind?: T;
  children?: T;
  assets?: T;
  tickets?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-categories_select".
 */
export interface AssetCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-statuses_select".
 */
export interface AssetStatusesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticket-types_select".
 */
export interface TicketTypesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  employeeId?: T;
  fullName?: T;
  company?: T;
  jobTitle?: T;
  phone?: T;
  email?: T;
  user?: T;
  team?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-teams_select".
 */
export interface MaintenanceTeamsSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  name?: T;
  assetTag?: T;
  company?: T;
  location?: T;
  category?: T;
  status?: T;
  serialNumber?: T;
  tonnage?: T;
  custodian?: T;
  defaultTeam?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-movements_select".
 */
export interface AssetMovementsSelect<T extends boolean = true> {
  reference?: T;
  asset?: T;
  company?: T;
  fromLocation?: T;
  toLocation?: T;
  movedBy?: T;
  movedAt?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  ticketNumber?: T;
  title?: T;
  description?: T;
  type?: T;
  priority?: T;
  status?: T;
  reviewStatus?: T;
  company?: T;
  location?: T;
  asset?: T;
  reportedBy?: T;
  reportedAt?: T;
  assignedTeam?: T;
  assignedTo?: T;
  activity?:
    | T
    | {
        kind?: T;
        author?: T;
        body?: T;
        photos?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}